<script setup lang="ts">
import { useLibraryAdminState } from "../../features/library/useLibraryAdminState";
import LibraryAssetColumn from "./library/LibraryAssetColumn.vue";
import LibraryFolderColumn from "./library/LibraryFolderColumn.vue";
import LibraryInspectorColumn from "./library/LibraryInspectorColumn.vue";
import AssetPanel from "./library/panels/AssetPanel.vue";
import EmbedPanel from "./library/panels/EmbedPanel.vue";
import FolderPanel from "./library/panels/FolderPanel.vue";
import OperationLogPanel from "./library/panels/OperationLogPanel.vue";

const {
  loading,
  savingFolder,
  savingAsset,
  savingEmbed,
  saving,
  feedback,
  feedbackError,
  fieldErrors,
  folders,
  selectedFolderId,
  folderAssets,
  deletedAssets,
  embedProfiles,
  categories,
  groups,
  folderName,
  folderCategoryId,
  createCoverFile,
  folderEditName,
  folderEditCategoryId,
  coverFile,
  assetFile,
  assetDisplayName,
  openMode,
  assetParserMode,
  assetEmbedProfileId,
  assetEmbedOptionsJson,
  editingAssetId,
  assetEditDisplayName,
  assetEditFolderId,
  assetEditOpenMode,
  assetEditParserMode,
  assetEditEmbedProfileId,
  assetEditEmbedOptionsJson,
  embedProfileName,
  embedScriptUrl,
  embedFallbackScriptUrl,
  embedViewerPath,
  embedConstructorName,
  embedAssetUrlOptionKey,
  embedExtensionsText,
  embedDefaultOptionsJson,
  embedEnabled,
  editingEmbedProfileId,
  embedEditName,
  embedEditScriptUrl,
  embedEditFallbackScriptUrl,
  embedEditViewerPath,
  embedEditConstructorName,
  embedEditAssetUrlOptionKey,
  embedEditExtensionsText,
  embedEditDefaultOptionsJson,
  embedEditEnabled,
  activePanelTab,
  folderSearchQuery,
  assetSearchQuery,
  profileSearchQuery,
  assetModeFilter,
  assetEmbedProfileFilter,
  assetSortMode,
  assetBatchMoveFolderId,
  selectedAssetIds,
  assetBatchResult,
  undoAssetIds,
  operationLogs,
  operationLogFilter,
  folderAssetsLoadSeq,
  panelSections,
  selectedFolder,
  groupedCategoryOptions,
  selectableEmbedProfiles,
  editingAsset,
  selectedFolderAssetCount,
  filteredFolders,
  filteredFolderAssets,
  sortedFilteredFolderAssets,
  filteredEmbedProfiles,
  selectedAssetCount,
  hasSelectedAssets,
  hasUndoAssets,
  filteredOperationLogs,
  allFilteredAssetsSelected,
  parseJsonObjectInput,
  syncFolderEditDraft,
  cancelAssetEdit,
  clearSelectedAssets,
  isAssetSelected,
  toggleAssetSelection,
  onAssetSelectChange,
  onSelectAllFilteredAssetsChange,
  cancelEmbedProfileEdit,
  setFeedback,
  setFieldError,
  clearFieldErrors,
  getFieldError,
  setActivePanelTab,
  isPanelSectionOpen,
  togglePanelSection,
  ensurePanelSectionOpen,
  formatOperationTime,
  pushOperationLog,
  clearOperationLogs,
  getApiErrorCode,
  setAssetBatchResult,
  onCreateCoverFileChange,
  onCoverFileChange,
  onAssetFileChange,
  reloadFolders,
  syncCategorySelection,
  syncFolderEditCategorySelection,
  reloadTaxonomy,
  reloadFolderAssets,
  reloadEmbedProfiles,
  createFolderEntry,
  saveFolderMeta,
  uploadCover,
  uploadAssetEntry,
  switchAssetOpenMode,
  runAssetBatchOpenMode,
  runAssetBatchMove,
  runAssetBatchDelete,
  runAssetBatchUndo,
  restoreDeletedAsset,
  removeDeletedAssetPermanently,
  startEditAsset,
  saveAssetEdit,
  createEmbedProfileEntry,
  startEditEmbedProfile,
  saveEmbedProfileEdit,
  removeEmbedProfile,
  syncEmbedProfileEntry,
  renameAssetDisplayName,
  removeAsset,
  removeFolder,
} = useLibraryAdminState();
</script>

<template src="./library/AdminLibraryView.template.html"></template>

<style scoped src="./library/AdminLibraryView.css"></style>
